-- indexes
SET @lower = CEILING((SELECT COUNT(LAT_N) FROM STATION)/2);
SET @upper = FLOOR(((SELECT COUNT(LAT_N) FROM STATION)/2)+1);

SET @one = 1;
SET @lower = @lower - 1;

PREPARE stmt FROM 'SELECT @i := ROUND(LAT_N,4) FROM STATION ORDER BY LAT_N DESC LIMIT ?,?';
EXECUTE stmt USING @lower, @one;

-- NOT COMPLETED! DATASET COUNT IS ODD SO TEST PASSES. BUT I NEED TO TAKE AVERAGE OF TWO NUMBER FOR EVEN DATASET COUNT